fixed workflow 1 and 2
Signed-off-by: Pranav Sunil Suryawanshi <pranavsur@cybage.com>

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -15,8 +15,8 @@ jobs:
        - name: Run Tests        
          id: run_tests        
          run: |          
-         echo "Running tests..."          # Simulate passing or failing tests          
-         exit 0  # Change to exit 1 to simulate a failure      
+           echo "Running tests..."          # Simulate passing or failing tests          
+           exit 0  # Change to exit 1 to simulate a failure      
            
        - name: Set output for job1        
          run: echo "::set-output name=test_status::${{ steps.run_tests.outcome }}" 
